protected/controllers/CategoryController.php
<?php

class CategoryController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
                //'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete', 'deleteChildCategories'),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Category;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Category'])) {
            $model->attributes = $_POST['Category'];
            $model->category_image = CUploadedFile::getInstance($model, 'category_image');
            $model->setAttribute('slug', $this->generate_slug($_POST['Category']['name']));
            if ($model->save()) {
                //$categpry_image_path = "D:/Public_html/yiitestdrive/images/category/" . $model->category_image->name;
                //$categpry_image_path = Yii::app()->baseUrl.'/images/category/'.$model->category_image->name;
                //$model->category_image->saveAs($categpry_image_path);
                //echo YiiBase::getPathOfAlias("webroot").'/images';
                $images_path = realpath(Yii::app()->basePath . '/../images/category');
                $model->category_image->saveAs($images_path . '/' . $model->category_image->name);

                Yii::app()->user->setFlash('success', 'Category created successfully.');
                $this->redirect($this->createUrl('admin'));
            }
            //$this->redirect(array('view','id'=>$model->id));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Category'])) {
            $model->attributes = $_POST['Category'];
            $model->category_image = CUploadedFile::getInstance($model, 'category_image');
            if ($model->save()) {
                if (isset($model->category_image)):

                    $images_path = realpath(Yii::app()->basePath . '/../images/category');
                    $model->category_image->saveAs($images_path . '/' . $model->category_image->name);
                    
                endif;

                Yii::app()->user->setFlash('success', 'Category updated successfully.');
                //Yii::app()->getUser()->setFlash('error','Could not save data to the database.');
                $this->redirect($this->createUrl('admin'));
                //	$this->redirect(array('view','id'=>$model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {

        $this->actionDeleteChildCategories($id);
        $this->loadModel($id)->delete();

        Yii::app()->user->setFlash('notice', 'Note : Deleted category has also deleted their subcategories.');

        Yii::app()->user->setFlash('success', 'Category deleted successfully.');
        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    public function actionDeleteChildCategories($parent_id) {
        $command = Yii::app()->db->createCommand();
        $command->delete('category', 'parent_id=:pid', array(':pid' => $parent_id));
        $command->reset();  // clean up the previous query
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Category');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Category('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Category']))
            $model->attributes = $_GET['Category'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Category the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Category::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Category $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'category-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/controllers/PageController.php
<?php

class PageController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column1';
	public $page_title = 'Manage pages';
	public $meta_desc = "this is default desc";
	public $focus_keywords = "this is default keywords";
	
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','getPages','show','to_slug'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$a = array(1,2,3);
		$b = "ashis narl";
		apt_pr($b);
		
		
		$model=new Page;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Page']))
		{
			$model->attributes=$_POST['Page'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}
		
		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Page']))
		{
			$model->attributes=$_POST['Page'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Page');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Page('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Page']))
			$model->attributes=$_GET['Page'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Page the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Page::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Page $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='page-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	public function actionGetPages(){

	$command = Yii::app()->db->createCommand();
	$pages = $command->select('*')->from('pages')->queryAll();
	return $pages;
	}

	public function actionShow($id = null,$title="null"){
	
		if($id == null)
		{
			throw new CHttpException(404,'Invalid page id');
			return $id;
		}
	
		$command = Yii::app()->db->createCommand('SELECT * FROM pages where id = '.$id);
		$page = $command->queryRow(); 
		$this->page_title = $page["page_title"];
		$this->meta_desc = $page["meta_desc"];
		$this->focus_keywords = $page["focus_keywords"];

		$this->render('get_page_details',array("page"=>$page));

		}
		public function to_slug($string){
    		return strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $string)));
		}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="language" content="en" />
		<?php
		$meta_title = isset($this->page_title) ? $this->page_title : CHtml::encode($this->pageTitle);
		$meta_keywords = isset($this->focus_keywords) ? $this->focus_keywords : "";
		$meta_desc = isset($this->meta_desc) ? $this->meta_desc : "";
		?>

		<meta name="description" content="<?php echo $meta_desc; ?>" />
		<meta name="keywords" content="<?php echo $meta_keywords; ?>" />
		<title><?php echo $meta_title; ?></title>
		<!-- blueprint CSS framework -->
		<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
		<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
		<!--[if lt IE 8]>
		<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
		<![endif]-->

		<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

        <!-- <title><?php echo CHtml::encode($this->pageTitle); ?></title> -->


		<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery-1.11.0.min.js"></script>
	</head>

	<body>

		<div class="container" id="page">

			<div id="header">
				<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
				<div  id="language-selector" style="float:right; margin:5px;">
					<?php
					$this->widget('application.components.widgets.LanguageSelector');
					?>
				</div>
				<?php
				$this->widget('application.components.widgets.LangBox');
				?>
			</div><!-- header -->


			<?php
			foreach (Yii::app()->user->getFlashes() as $key => $message) {
				if ($key == 'counters') {
					continue;
				}
				echo "<div class='flash-{$key}'>{$message}</div>";
			}
			Yii::app()->clientScript->registerScript(
				'myHideEffect', '$(".flash-success,.flash-notice,.flash-error").animate({opacity: 1.0}, 3000).fadeOut("slow");', CClientScript::POS_READY
			);
			?>

			<?php
			$page = Yii::app()->createController('page'); //returns array containing controller instance and action index.
			$page = $page[0]; //get the controller instance.

			$page_info = $page->actionGetPages(); //use a public method.
			$pages_header_items = array();
			$pages_footer_items = array();
			foreach ($page_info as $p_key => $p_value) {

				$route = "page/show";

				$params = "";
				$url = "";
				//$params = array("id"=>$p_value['id']);
				$params = array("id" => $p_value['id'], "title" => $p_value['seo_title']);

				//$url = $this->createUrl($route,$params);
				$url = $this->createAbsoluteUrl($route, $params);
				//echo $url."<br/>";


				if ($p_value["menu_option"] == "headmenu")
					array_push($pages_header_items, array('label' => $p_value['page_title'], 'url' => $url));

				if ($p_value["menu_option"] == "footmenu")
					array_push($pages_footer_items, array('label' => $p_value['page_title'], 'url' => $url));
			}
			$header_items = array(
			    array('label' => 'Home', 'url' => array('/site/index')),
			    array('label' => 'About', 'url' => array('/site/page', 'view' => 'about')),
			    array('label' => 'Contact', 'url' => array('/site/contact')),
			    array('label' => 'Pages', 'url' => '', 'items' => $pages_header_items, 'visible' => Yii::app()->user->isGuest),
			    array('label' => 'CMS', 'url' => array('/page/admin'), 'items' => $this->page_menu, 'visible' => !Yii::app()->user->isGuest),
			    array('label' => 'Category', 'url' => array('/category/admin'), 'items' => $this->category_menu, 'visible' => !Yii::app()->user->isGuest),
			    array('url' => Yii::app()->getModule('user')->loginUrl, 'label' => Yii::app()->getModule('user')->t("Login"), 'visible' => Yii::app()->user->isGuest),
			    array('url' => Yii::app()->getModule('user')->registrationUrl, 'label' => Yii::app()->getModule('user')->t("Register"), 'visible' => Yii::app()->user->isGuest),
			    array('url' => Yii::app()->getModule('user')->profileUrl, 'label' => Yii::app()->getModule('user')->t("Profile"), 'visible' => !Yii::app()->user->isGuest),
			    array('url' => Yii::app()->getModule('user')->logoutUrl, 'label' => Yii::app()->getModule('user')->t("Logout") . ' (' . Yii::app()->user->name . ')', 'visible' => !Yii::app()->user->isGuest),
			);

			$footer_items = array(
			    array('label' => 'Home', 'url' => array('/site/index')),
			    // array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
			    // array('label'=>'Contact', 'url'=>array('/site/contact')),
			    array('label' => 'Pages', 'url' => '', 'items' => $pages_footer_items, 'visible' => Yii::app()->user->isGuest),
			    array('label' => 'CMS', 'url' => array('/page/admin'), 'items' => $this->page_menu, 'visible' => !Yii::app()->user->isGuest),
			    array('label' => 'Category', 'url' => array('/category/admin'), 'items' => $this->category_menu, 'visible' => !Yii::app()->user->isGuest),
			    array('label' => 'Login', 'url' => array('/site/login'), 'visible' => Yii::app()->user->isGuest),
			    array('label' => 'Logout (' . Yii::app()->user->name . ')', 'url' => array('/site/logout'), 'visible' => !Yii::app()->user->isGuest),
			);
			?>
			<div id="mainmenu">
				<?php
				$this->widget('zii.widgets.CMenu', array('items' => $header_items, 'encodeLabel' => false,
				    'htmlOptions' => array(
					'class' => 'nav pull-right',
				    ),
				    'submenuHtmlOptions' => array(
					'class' => 'dropdown-menu',
				)));
				?>
			</div><!-- mainmenu -->
			<!-- slider start -->
			<?php
			/*
			  $this->widget('application.extensions.slider.Slider',array(
			  'items'=>array(
			  array(Yii::app()->getBaseUrl(true).'/images/img1.png', 'image1'),
			  array(Yii::app()->getBaseUrl(true).'/images/img2.png', 'image2'),
			  array(Yii::app()->getBaseUrl(true).'/images/img3.png', 'image3'),
			  array(Yii::app()->getBaseUrl(true).'/images/img4.png', 'image4'),
			  array(Yii::app()->getBaseUrl(true).'/images/img5.png', 'image5'),
			  ),
			  )); */
			?>
			<!-- slider end --> 
			<?php if (isset($this->breadcrumbs)): ?>
				<?php
				$this->widget('zii.widgets.CBreadcrumbs', array(
				    'links' => $this->breadcrumbs,
				));
				?><!-- breadcrumbs -->
			<?php endif ?>

			<?php echo $content; ?>

			<div class="clear"></div>

			<div id="footer">
				<?php
				$this->widget('application.extensions.social.social', array(
				    'style' => 'vertical',
				    'networks' => array(
					'twitter' => array(
					    'data-via' => '', //http://twitter.com/#!/YourPageAccount if exists else leave empty
					),
					'googleplusone' => array(
					    "size" => "medium",
					    "annotation" => "bubble",
					),
					'facebook' => array(
					    'href' => 'https://www.facebook.com/NarolaInfotech', //asociate your page http://www.facebook.com/page 
					    'action' => 'recommend', //recommend, like
					    'colorscheme' => 'light',
					    'width' => '120px',
					)
				    )
				));

				/*
				 * Usual parameters to be adjusted: 

				  - style: button's alignment (string: horizontal or vertical).
				  - networks: social network which you must have (twitter, googleplusone, facebook);
				  - data-via:Your Twitter Page Account if exists or leave empty (url: //http://twitter.com/#!/YourPageAccount)
				  - size: google button size (string:small, standard, **medium**, tall)
				  - annotation: google button mode to show annotation(string: **bubble**, inline, none)
				  - href: Your Facebook Page (url: http://www.facebook.com/facebook_page)
				  - action: action for facebook button (string: **recommend** or like)
				  - colorscheme: used color scheme for facebook button (string: **light** or dark)
				  - width: the width for facebook button container (pixels: **120px**)
				 */
				?>
				<div id="footer_links">
					<?php $this->widget('zii.widgets.CMenu', array('items' => $footer_items)); ?>	
				</div>

				<div class="copyright">
					Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
					All Rights Reserved.<br/>
					<?php echo Yii::powered(); ?>
				</div>
			</div><!-- footer -->

		</div><!-- page -->


	</body>
</html>